sudo: required
services:
  - docker

before_install:
  - docker build -t marinaromanova/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true marinaromanova/react-test npm test -- --coverage

after_success:
#build production images for every part of the project
  - docker build -t marinaromanova/multi-client ./client
  - docker build -t marinaromanova/multi-nginx ./nginx
  - docker build -t marinaromanova/multi-server ./server
  - docker build -t marinaromanova/multi-worker ./worker
#login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#take the built images and push them to docker hub
  - docker push marinaromanova/multi-client
  - docker push marinaromanova/multi-nginx
  - docker push marinaromanova/multi-server
  - docker push marinaromanova/multi-worker